Repository qiskit-community/qiskit-braket-provider, pull requests merged in 2022-06, with the labels that each got.

#38 Update to provider due to launch of Xanadu device
  qiskit_braket_provider/providers/adapter.py
  qiskit_braket_provider/providers/braket_provider.py
  requirements.txt
Labels: bug, enhancement

#40 Update Amazon Braket user agent
  qiskit_braket_provider/providers/braket_backend.py
  requirements.txt
  tests/providers/test_braket_backend.py
  tox.ini
Labels: enhancement

#43 Docs: update tutorial
  .pylintrc
  docs/tutorials/0_tutorial_qiskit-braket-provider_overview.ipynb
  docs/tutorials/data/qiskit-braket-mapping.png
  docs/tutorials/data/qiskit-to-braket-diagram.png
Labels: documentation
