Repository qiskit-community/qiskit-braket-provider, pull requests merged in 2022-05, with the labels that each got.

#24 Refactor: rework of job result + adding measure instruction to target
  docs/how_tos/example_how_to.ipynb
  docs/tutorials/1_vqe.ipynb
  docs/tutorials/example_tutorial.ipynb
  qiskit_braket_plugin/providers/adapter.py
  qiskit_braket_plugin/providers/braket_backend.py
  qiskit_braket_plugin/providers/braket_job.py
  requirements.txt
  tests/providers/test_braket_backend.py
Labels: bug, documentation, enhancement

#28 Issue 27 | Workflows: release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: documentation, enhancement

#29 Workflows: drafter branch change
  .github/workflows/release-drafter.yml
Labels: bug

#31 Issue-6 | Workflows: release to Pypi and upload artifact
  .github/workflows/release-package.yml
  qiskit_braket_provider/VERSION.txt
  setup.py
Labels: enhancement

#32 Release prep
  .github/workflows/release-package.yml
  README.md
  docs/installation_guide.md
  docs/quickstart_guide.md
  requirements.txt
  setup.py
Labels: documentation

#30 how to qiskit hybrid job
  docs/how_tos/3_how_to_qiskit_hybrid_job.ipynb
  docs/images/aws_uri.png
Labels: documentation

#33 Issue #4 | hybrid jobs tutorial
  docs/how_tos/3_how_to_qiskit_hybrid_job.ipynb
  docs/how_tos/data/3_hybrid_jobs/Dockerfile
  docs/how_tos/data/3_hybrid_jobs/algorithm_script.py
  docs/images/aws_uri.png
  docs/tutorials/1_tutorial_vqe.ipynb
  docs/tutorials/2_tutorial_hybrid_jobs_byoc.ipynb
  docs/tutorials/data/2_hybrid_jobs/Dockerfile
  docs/tutorials/data/2_hybrid_jobs/job_script.py
  tests/providers/test_braket_backend.py
  tox.ini
Labels: documentation

#34 Tutorials: minimum eigen optimizer
  docs/tutorials/3_tutorial_minimum_eigen_optimizer.ipynb
  tox.ini
Labels: documentation

#36 Tutorials: overview
  docs/tutorials/0_tutorial_qiskit-braket-provider_overview.ipynb
  docs/tutorials/data/qiskit-to-braket-diagram.png
Labels: documentation
